name: Setup
description: Setup Python, dependencies, caching, etc.
inputs:
  python-version:
    description: Python version to use
    required: false
    default: '3.11'
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Generate .env fro .env.sample
      shell: bash
      run: cp .env.sample .env

    - name: Install Python dependencies
      shell: bash
      run: make install

