repos:
  - repo: local
    hooks:
      - id: lint
        name: Run lint
        entry: make lint
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: unit-test
        name: Run make test
        entry: make test
        language: system
        pass_filenames: false
        stages: [pre-push]
